import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import { mergeSort } from "../algorithms/mergeSort";
import Element from "../components/Element";
import styles from "../styles/Home.module.css";

class Bar {
  constructor(value, backgroundColor) {
    this.value = value;
    this.backgroundColor = backgroundColor;
  }
}

export default function Home() {
  const randomNumber = (min, max) => {
    return Math.floor(Math.random() * (max - min) + min);
  };

  const generateRandomArray = (bars, height) => {
    let arr = [];

    for (let i = 0; i < bars; i++) {
      const element = new Bar(randomNumber(5, height), "blue");
      arr.push(element);
    }

    return arr;
  };

  const [array, setArray] = useState([]);
  const [bars, setBars] = useState(0);
  const [height, setHeight] = useState(0);
  const arrRef = useRef();
  const containerRef = useRef();

  useEffect(() => {
    const findBars = () => {
      let width = arrRef.current.clientWidth;
      let height = containerRef.current.clientHeight / 1.5;
      let bars = Math.floor(width / 4);
      setBars(bars);
      setHeight(height);
    };
    window.onresize = findBars;
    findBars();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    setArray(generateRandomArray(bars, height));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [bars, height]);
  console.log(array);

  const checkWorked = () => {
    const sortedArray = array.slice().sort((a, b) => a - b);
    const mergeSortedArray = mergeSort(array.slice());
    console.log(checkIfCorrect(sortedArray, mergeSortedArray));
  };

  const checkIfCorrect = (sortedArray, mergeSortedArray) => {
    for (let i = 0; i < sortedArray.length; i++) {
      if (sortedArray[i] !== mergeSortedArray[i]) {
        return false;
      }
    }
    return true;
  };

  const animateMergeSort = () => {};

  return (
    <div ref={containerRef} className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div ref={arrRef} className={styles.array}>
        {array.map(({ value, backgroundColor }, index) => (
          <Element
            key={index}
            value={value}
            backgroundColor={backgroundColor}
          />
        ))}
      </div>
      <div style={{ display: "flex" }}>
        <button onClick={() => setArray(generateRandomArray(bars, height))}>
          Generate New Array
        </button>
        <button onClick={() => animateMergeSort()}>Merge Sort</button>
        <button onClick={() => setArray(generateRandomArray(bars, height))}>
          Quick Sort
        </button>
        <button onClick={() => setArray(generateRandomArray(bars, height))}>
          Bubble Sort
        </button>
        <button onClick={() => setArray(generateRandomArray(bars, height))}>
          Heap Sort
        </button>
      </div>
    </div>
  );
}
