import Head from "next/head";
import { useEffect, useState } from "react";
import Element from "../components/Element";
import styles from "../styles/Home.module.css";

export default function Home() {
  const randomNumber = (min, max) => {
    return Math.floor(Math.random() * (max - min) + min);
  };

  const generateRandomArray = () => {
    let arr = [];

    for (let i = 5; i < 360; i++) {
      arr.push(randomNumber(5, 360));
    }

    return arr;
  };

  const [array, setArray] = useState([]);

  useEffect(() => {
    let width = window.innerWidth;
    let bars = Math.floor(width / 4);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.array}>
        {array.map((number, index) => (
          <Element key={index} number={number} />
        ))}
      </div>
    </div>
  );
}
